### ISSUE TITLE
Must be an array or object... 0.10.2

### ISSUE THREAD

**Issue by BaseCampFilms** [techtimo/spotmap#13]
Hi there, have just installed Spotmap and am getting the following errors:

Warning: count(): Parameter must be an array or an object that implements Countable in /home/wildeye/webapps/bcfwordpress/wp-content/plugins/spotmap/admin/class-spotmap-admin.php on line 31

Warning: Cannot modify header information - headers already sent by (output started at /home/wildeye/webapps/bcfwordpress/wp-content/plugins/spotmap/admin/class-spotmap-admin.php:31) in /home/wildeye/webapps/bcfwordpress/wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at /home/wildeye/webapps/bcfwordpress/wp-content/plugins/spotmap/admin/class-spotmap-admin.php:31) in /home/wildeye/webapps/bcfwordpress/wp-admin/admin-header.php on line 9

**Comment by BaseCampFilms** [comment]
Running PHP 7.1 removes this error, Wordpress however is asking for me to update to 7.4

**Comment by techtimo** [comment]
Hi,

I was in the mountains this weekend. I will investigate tomorrow.

Thanks for raising the issue.

Il sab 22 mag 2021, 20:45 BaseCampFilms ***@***.***> ha
scritto:

**Comment by techtimo** [comment]
Hi BaseCampFilms,

I was actually still developing and only verifying on PHP7.1.
I have updated my dev environment to PHP7.4. Currently I'm working on some front end changes, I will verify everything and probably push out the new version to Wordpress.org later this weekend.

It comes with some changes I developed in the last weeks.
Have you you used it on PHP7.1 a bit? If you would like to have some minor change included let me know.

/Timo

**Comment by BaseCampFilms** [comment]
Thank you for developing this plugin, it works beautifully. I have downgraded my PHP to 7.1 at the moment for it to run.

Minor changes, not all the lastest TF maps are included in maps.json, I went in and added a couple.

I realise this isn't a minor change, but, would love to see...

Under the settings tab have a list of the waypoints which can also be removed. Also would love a way to be able to add an image from the WP media library to each waypoint that could be displayed on the pop-up box on the map, maybe something for the future...?

Thanks for what you are doing!

**Comment by BaseCampFilms** [comment]
Instead of images, how about a link to a blog entry...?

**Comment by techtimo** [comment]
You are thinking about different images on the same type of point right?
There it would rather be a good option to select certain photos from the media library and read the geo location in the EXIF data and display this point on the map.
In fact I haven't seen a good wordpress plugin that is able to do this. I would wish to have this also in my blog, but I must admit this will not come in the near future.
For the links to blog entries I feel quite similar: Rather then adding a link to a point, I would prefer to have a geo tag included in the wordpress post, and then filter for a certain date range and show all blog posts with a geotag from this range. But this requires some more modifications inside of Wordpress, which will not happen in the near future either. 
A possible solution might be to compile a gpx that contains waypoints in a specific format to include at least specific text and links or similar.


Something to think about.. But I must be honest, there are weeks/months where I'm quite motivated and some improvements are made. And then there are longer times where not so much is happening.
But also the more people using the plugin will push me to develope more :)

Currently I'm in contact with a guy who owns a Garmin inReach to see if it'll be possible to integrate this as well in the plugin.
The release where your issue is fixed will include some new elements like a configurable icon for every message type send by the spot, and hopefully also the TF maps you were missing.
![grafik](https://user-images.githubusercontent.com/22075114/120028751-6528d680-bff5-11eb-9cde-d15473ac77da.png)

**Comment by techtimo** [comment]
Hi BaseCampFilms,

I just pushed the latest addition on github. You may try the new version if you download the zip file from here:
https://github.com/techtimo/Spotmap/archive/refs/heads/master.zip

you might need to deactivate and activate the plugin, in order to trigger some code that is running for the upgrade.

Make sure to backup your maps.json becasue with the update it will be overwritten.
I won't push this version to wordpress.org yet, as currently this version hasn't been tested much. As it introduces some changes I like to verify it further and also do some more cleanup of old code I have written long time ago. and I would like to ahve some options customizable. (e.g. the arrows in the line.)

Please feel free to download this new version and provide some feedback :)


Cheers, 
Timo

**Comment by techtimo** [comment]
I'm closing this issue. Feel free to reopen if you experience any other PHP related issues on the current version.

- Timo
